### PR TITLE
Fixed package.json libraries paths

### PR DESCRIPTION
**Pull request by floatdrop**
* Use react from jspm registry
 * Use react-addons from npm (instead of react from bower)
 * Use jsx plugin from jspm registry

### CODE REVIEW

**Comment by floatdrop** [comment]
Just found https://github.com/toxicFork/jsx-plugin — I wonder, is it right to use `react-bower`, instead of `react`, feel free to close this one.

**Comment by toxicFork** [comment]
I used react bower because jspm:react was not working (and the jspm:jsx as well), will check how react-addons works :)

**Comment by floatdrop** [comment]
@toxicFork you don't need to prefix them with `jspm:` and it will be ok.

**Comment by toxicFork** [comment]
Yes I used jspm: prefix to note that I was using the jspm registry sorry, I meant "jspm install react" and "jspm install jsx", for example when I install the default jsx, it comes with react tools which is missing lots of files, could be because I'm on a Windows machine and the forward or back slashes are confusing the module loader or something...

**Comment by toxicFork** [comment]
E.g.

```bash
jspm install npm:react-tools
```

Looking into the jspm_packages/npm/react-tools@0.12.2, the main.js has on line 4: 

```JavaScript
require("./vendor\fbtransform\visitors");
```

And in the src/vendor folder, all the directories are empty

**Comment by toxicFork** [comment]
image

Tried it in another windows computer and same result :(

**Comment by toxicFork** [comment]
@floatdrop i see that jspm-cli has a new release to fix things for windows, when that one is deployed i shall merge this pull :)

**Comment by floatdrop** [comment]
@toxicFork yeah, Windows is sometimes hard. :)

**Pull request merged**
